version: '3.7'
services:
  mongo:
    env_file: .env
    image: mongo:7.0.8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - mongo_data:/data/db

  trade-union:
    build: .
    network_mode: "host"
    ports:
      - "8099:8099"

volumes:
  mongo_data:
